get_open_sensors:
  fields:
    only_alerts:
      required: false
      example: true

adjust_remaining_seconds:
  fields:
    entity_id:
      required: true
    seconds:
      required: true

dismiss_alert:
  fields:
    entity_id:
      required: true